Repository hmcts/adoption-frontend, pull requests merged in 2020-02, with the labels that each got.

#13 FPLA-1236 - fix local docker
  Dockerfile
  README.md
  charts/adoption-frontend/Chart.yaml
  charts/adoption-frontend/values.aat.template.yaml
  charts/adoption-frontend/values.preview.template.yaml
  charts/adoption-frontend/values.yaml
  package.json
Labels: ns:adoption, rel:adoption-frontend-pr-13

#14 FPLA-1348 fix for i18n config
  package.json
  src/main/locales/en/translation.json
  src/main/modules/i18n/backend.ts
  src/main/modules/i18n/index.ts
  src/main/views/home.njk
  yarn.lock
Labels: ns:adoption, rel:adoption-frontend-pr-14

#21 Fix sonar failure and add dependancies for idam integration
  package.json
  src/main/app.ts
  tsconfig.json
  yarn.lock
Labels: ns:adoption, rel:adoption-frontend-pr-21

#22 Apply express template changes
  .gitignore
  README.md
  config/default.json
Labels: ns:adoption, rel:adoption-frontend-pr-22

#23 Dev/test 2
  README.md
Labels: ns:adoption, rel:adoption-frontend-pr-23
