Repository hmcts/adoption-frontend, pull requests merged in 2020-04, with the labels that each got.

#42 Idam config setup for preview and aat
  charts/adoption-frontend/Chart.yaml
  charts/adoption-frontend/requirements.yaml
  charts/adoption-frontend/values.preview.template.yaml
  charts/adoption-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  package.json
  server.js
  src/main/app.ts
  src/main/app/idam/authorizationMiddleware.ts
  src/main/app/idam/idamClient.ts
  src/main/modules/secrets/index.ts
  src/main/routes/landing.ts
  src/main/server.ts
Labels: ns:adoption, rel:adoption-frontend-pr-42

#45 Terraform clean up
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:adoption, rel:adoption-frontend-pr-45

#46 Reorder imports
  src/main/server.ts
Labels: ns:adoption, rel:adoption-frontend-pr-46
