Repository hmcts/adoption-frontend, pull requests merged in 2020-03, with the labels that each got.

#32 bug - Add i18next to nunjucks constructor
  .eslintignore
  src/main/modules/nunjucks/index.ts
  tslint.json
Labels: ns:adoption, rel:adoption-frontend-pr-32

#28 feat:configure secrets and app insight
  charts/adoption-frontend/Chart.yaml
  charts/adoption-frontend/values.yaml
  src/main/app.ts
  src/main/modules/appinisght/index.ts
  src/main/modules/secrets/index.ts
  src/test/modules/appinsight/appinsight.ts
  src/test/modules/secrets/secrets.ts
Labels: ns:adoption, rel:adoption-frontend-pr-28

#34 Fix secrets test
  src/test/modules/secrets/secrets.ts
Labels: ns:adoption, rel:adoption-frontend-pr-34

#35 Add object-curly-spacing lint rule and fix issues
  .eslintrc.js
  src/main/app.ts
  src/main/modules/appinisght/index.ts
  src/main/modules/secrets/index.ts
  src/test/modules/appinsight/appinsight.ts
  src/test/modules/secrets/secrets.ts
Labels: ns:adoption, rel:adoption-frontend-pr-35

#27 feat: task list page framework (FPLA-1223)
  .dockerignore
  .github/workflows/checks.yml
  .gitignore
  .sass-lint.yml
  Dockerfile
  README.md
  gulpfile.js
  integration-tests.Dockerfile
  package.json
  src/main/app.ts
  src/main/app/case/types/alert/alert.ts
  src/main/app/case/types/index.ts
  src/main/app/case/types/task-list/enum/taskStatus.ts
  src/main/app/case/types/task-list/index.ts
  src/main/app/case/types/task-list/subTask.ts
  src/main/app/case/types/task-list/task.ts
  src/main/app/case/types/task-list/taskList.ts
  src/main/app/case/util/subTaskListBuilder.ts
  src/main/assets/scripts/main.ts
  src/main/assets/scss/adoption/components/alert/_alert.scss
  src/main/assets/scss/adoption/components/index.scss
  src/main/assets/scss/adoption/components/task-list/_task-list.scss
  src/main/assets/scss/adoption/util/index.scss
  src/main/assets/scss/adoption/util/spacing/_spacing.scss
  src/main/assets/scss/main.scss
  src/main/index.ts
  src/main/locales/cy/common.json
  src/main/locales/en/common.json
  src/main/locales/en/taskList.json
  src/main/locales/en/translation.json
  src/main/modules/i18n/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/webpack/app.ts
  src/main/modules/webpack/govukFrontend.ts
  src/main/modules/webpack/scss.ts
  src/main/public/img/favicon.ico
  src/main/routes/task-list.ts
  src/main/views/error.njk
  src/main/views/home.njk
  src/main/views/layouts/default.layout.njk
  src/main/views/macros/alert/alert.njk
  src/main/views/macros/page-heading/page-heading.njk
  src/main/views/macros/task-list/sub-task-list.njk
  src/main/views/macros/task-list/task-list.njk
  src/main/views/not-found.njk
  src/main/views/task-list.njk
  src/test/a11y/a11y.ts
  src/test/app/case/types/alert/alert.ts
  src/test/app/case/types/task-list/task-list.ts
  src/test/routes/task-list.ts
  tsconfig.json
  webpack.config.ts
  yarn.lock
Labels: ns:adoption, rel:adoption-frontend-pr-27

#30 FPLA-1322: Idam integration
  .eslintignore
  .eslintrc.js
  config/default.json
  package.json
  src/main/app.ts
  src/main/app/case/index.ts
  src/main/app/common/router/routablePath.ts
  src/main/app/common/utils/buildURL.ts
  src/main/app/common/utils/errorHandling.ts
  src/main/app/common/utils/stringUtils.ts
  src/main/app/idam/AuthToken.ts
  src/main/app/idam/authorizationMiddleware.ts
  src/main/app/idam/idamClient.ts
  src/main/app/idam/jwtExtractor.ts
  src/main/app/idam/oAuthHelper.ts
  src/main/app/idam/user.ts
  src/main/app/paths.ts
  src/main/routes/home.ts
  src/main/routes/landing.ts
  src/test/a11y/a11y.ts
  src/test/app/case/index.ts
  src/test/app/common/router/routablePath.ts
  src/test/app/common/utils/buildURL.ts
  src/test/app/common/utils/errorHandling.ts
  src/test/app/common/utils/stringUtils.ts
  src/test/app/idam/OAuthHelper.ts
  src/test/app/idam/authorizationMiddleware.ts
  src/test/app/idam/idamClient.ts
  src/test/http-mocks/idam/idam.ts
  src/test/routes/home.ts
  src/test/routes/landing.ts
  tsconfig.json
  yarn.lock
Labels: ns:adoption, rel:adoption-frontend-pr-30

#36 fix: webpack nodemon fixes
  nodemon.json
  package.json
  yarn.lock
Labels: ns:adoption, rel:adoption-frontend-pr-36

#37 FPLA-1223: Redirect to task-list changes
  config/default.json
  src/main/app/case/index.ts
  src/main/app/case/paths.ts
  src/main/app/case/routes/task-list.ts
  src/main/app/case/views/task-list.njk
  src/main/app/common/router/routablePath.ts
  src/main/app/paths.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/landing.ts
  src/main/routes/task-list.ts
  src/test/a11y/a11y.ts
  src/test/a11y/mocks.ts
  src/test/app/case/routes/route-authorization.ts
  src/test/app/case/routes/task-list.ts
  src/test/app/common/router/routablePath.ts
  src/test/app/idam/authorizationMiddleware.ts
  src/test/routes/landing.ts
  src/test/routes/task-list.ts
Labels: ns:adoption, rel:adoption-frontend-pr-37

#38 Bug: Fix task list page load issue
  src/main/views/layouts/default.layout.njk
  webpack.config.ts
Labels: ns:adoption, rel:adoption-frontend-pr-38

#40 Setup nodemon debugger
  README.md
  nodemon.json
Labels: ns:adoption, rel:adoption-frontend-pr-40

#41 Logout functionality
  src/main/app/idam/idamClient.ts
  src/main/app/paths.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/logout.ts
  src/main/views/layouts/default.layout.njk
  src/test/routes/logout.ts
Labels: ns:adoption, rel:adoption-frontend-pr-41

#43 Rename to appinsights
  src/main/app.ts
  src/main/modules/appinsights/index.ts
  src/test/modules/appinsights/appinsights.ts
Labels: ns:adoption, rel:adoption-frontend-pr-43
